const WORD_DATA = {
  names: {
    label: "Names",
    icon: "👤",
    color: "#FF6B9D",
    words: [
      { word: "ALEXANDER", hint: "A great conqueror from Macedonia" },
      { word: "SOPHIA", hint: "A popular name meaning wisdom" },
      { word: "BENJAMIN", hint: "A Hebrew name meaning son of the right hand" },
      { word: "ISABELLA", hint: "A name meaning devoted to God" },
      { word: "MUHAMMAD", hint: "Most common name in the world" },
      { word: "CHARLOTTE", hint: "A French feminine name" },
      { word: "SEBASTIAN", hint: "A name of Greek origin meaning venerable" },
      { word: "VALENTINA", hint: "A name meaning strong and healthy" },
      { word: "NATHANIEL", hint: "A Hebrew name meaning gift of God" },
      { word: "ELIZABETH", hint: "A classic royal name" },
      { word: "DOMINIQUE", hint: "A name meaning belonging to God" },
      { word: "FREDERICK", hint: "A Germanic name meaning peaceful ruler" },
      { word: "CASSANDRA", hint: "A prophetess from Greek mythology" },
      { word: "THEODORE", hint: "A name meaning gift of God" },
      { word: "GABRIELLE", hint: "Feminine form of Gabriel" },
      { word: "Rohan Jabeel", hint: "Famous Urdu Novel Character" },
      { word: "Sheriyar", hint: "Muslim Boy Name" },
      { word: "Babar Azam", hint: "Famous Pakistani Cricketer" },
      { word: "Virat Kholi", hint: "World Wide Cricketer" },
      { word: "Hania Amir", hint: "Dimple Girl" },
      { word: "Hezlin", hint: "Girl Name Start with H" },

    ]
  },
  flowers: {
    label: "Flowers",
    icon: "🌸",
    color: "#FF9F43",
    words: [
      { word: "SUNFLOWER", hint: "Tall yellow flower that follows the sun" },
      { word: "LAVENDER", hint: "Purple aromatic flower used in perfumes" },
      { word: "CHRYSANTHEMUM", hint: "Flower often used in Asian cultures" },
      { word: "DANDELION", hint: "You blow its seeds and make a wish" },
      { word: "MARIGOLD", hint: "Bright orange or yellow flower" },
      { word: "BLUEBELL", hint: "Nodding blue bell-shaped wildflower" },
      { word: "JASMINE", hint: "Fragrant white flower used in tea" },
      { word: "HIBISCUS", hint: "Tropical flower, national flower of Malaysia" },
      { word: "DAFFODIL", hint: "Yellow spring flower with a trumpet center" },
      { word: "MAGNOLIA", hint: "Large white or pink flower on a tree" },
      { word: "PETUNIA", hint: "Funnel-shaped garden flower" },
      { word: "FOXGLOVE", hint: "Tall spike with bell-shaped flowers" },
      { word: "BUTTERCUP", hint: "Small shiny yellow wildflower" },
      { word: "PRIMROSE", hint: "Early spring flower, often pale yellow" },
      { word: "WISTERIA", hint: "Purple hanging clusters of flowers" },
    ]
  },
  countries: {
    label: "Countries",
    icon: "🌍",
    color: "#48DBFB",
    words: [
      { word: "PAKISTAN", hint: "South Asian country, home to K2" },
      { word: "ARGENTINA", hint: "South American country famous for tango" },
      { word: "MOZAMBIQUE", hint: "African country on the Indian Ocean coast" },
      { word: "SWITZERLAND", hint: "European country famous for watches and cheese" },
      { word: "MADAGASCAR", hint: "Large island nation off Africa's coast" },
      { word: "AZERBAIJAN", hint: "Country in the South Caucasus region" },
      { word: "PHILIPPINES", hint: "Archipelago of 7000+ islands in Southeast Asia" },
      { word: "BANGLADESH", hint: "South Asian country known for the Sundarbans" },
      { word: "CAMBODIA", hint: "Home of the Angkor Wat temple" },
      { word: "ZIMBABWE", hint: "African country with Victoria Falls" },
      { word: "KAZAKHSTAN", hint: "Largest landlocked country in the world" },
      { word: "VENEZUELA", hint: "South American country with Angel Falls" },
      { word: "INDONESIA", hint: "World's largest archipelago nation" },
      { word: "ETHIOPIA", hint: "African country known as the cradle of humanity" },
      { word: "PORTUGAL", hint: "Western European country, birthplace of explorers" },
    ]
  },
  plants: {
    label: "Plants",
    icon: "🌿",
    color: "#1DD1A1",
    words: [
      { word: "CACTUS", hint: "Desert plant that stores water in its stems" },
      { word: "BAMBOO", hint: "Fast-growing grass loved by pandas" },
      { word: "MANGROVE", hint: "Tree that grows in coastal saltwater" },
      { word: "FERN", hint: "Ancient plant with feathery fronds" },
      { word: "SEQUOIA", hint: "Tallest living trees on Earth" },
      { word: "ALOE", hint: "Succulent used for soothing burns" },
      { word: "PITCHER", hint: "Carnivorous plant that traps insects in liquid" },
      { word: "BONSAI", hint: "Japanese art of miniature trees" },
      { word: "ORCHID", hint: "Exotic flowering plant with 25,000 species" },
      { word: "VENUS", hint: "Carnivorous plant with a snap trap" },
      { word: "EUCALYPTUS", hint: "Australian tree loved by koalas" },
      { word: "TUMBLEWEED", hint: "Rolling desert plant carried by wind" },
      { word: "SUNDEW", hint: "Carnivorous plant with sticky tentacles" },
      { word: "BANYAN", hint: "Tree with aerial roots forming extra trunks" },
      { word: "CATTAIL", hint: "Wetland plant with brown sausage-like top" },
    ]
  },
  cars: {
    label: "Cars",
    icon: "🚗",
    color: "#FF6348",
    words: [
      { word: "LAMBORGHINI", hint: "Italian supercar brand with a bull logo" },
      { word: "FERRARI", hint: "Italian sports car brand with a prancing horse" },
      { word: "MUSTANG", hint: "Iconic American muscle car by Ford" },
      { word: "BUGATTI", hint: "Hyper car brand known for the Veyron" },
      { word: "PORSCHE", hint: "German car brand known for the 911" },
      { word: "MASERATI", hint: "Italian luxury car with a trident logo" },
      { word: "CHEVROLET", hint: "American car brand with a bowtie logo" },
      { word: "VOLKSWAGEN", hint: "German brand meaning 'people's car'" },
      { word: "BENTLEY", hint: "British ultra-luxury car brand" },
      { word: "CADILLAC", hint: "American luxury car, often used by presidents" },
      { word: "MCLAREN", hint: "British supercar brand from a racing team" },
      { word: "PAGANI", hint: "Italian hypercar maker known for the Huayra" },
      { word: "KOENIGSEGG", hint: "Swedish hypercar brand" },
      { word: "ASTON", hint: "British car brand with a DB series" },
      { word: "ROLLS", hint: "Ultra-luxury British car brand" },
    ]
  },
  things: {
    label: "Things",
    icon: "🎒",
    color: "#A29BFE",
    words: [
      { word: "TELESCOPE", hint: "Used to see distant stars and planets" },
      { word: "COMPASS", hint: "Navigation tool that always points north" },
      { word: "BINOCULARS", hint: "Two lenses for seeing far away objects" },
      { word: "MICROSCOPE", hint: "Used to see very tiny things" },
      { word: "CALCULATOR", hint: "Electronic device for math" },
      { word: "THERMOMETER", hint: "Measures how hot or cold something is" },
      { word: "PARACHUTE", hint: "Safety device used when jumping from a plane" },
      { word: "SUBMARINE", hint: "Vehicle that travels underwater" },
      { word: "LIGHTHOUSE", hint: "Tall tower with a light to guide ships" },
      { word: "PERISCOPE", hint: "Used in submarines to see above water" },
      { word: "METRONOME", hint: "Device that keeps musical tempo" },
      { word: "KALEIDOSCOPE", hint: "Tube with mirrors and colored pieces" },
      { word: "HARMONICA", hint: "Small mouth-blown musical instrument" },
      { word: "BOOMERANG", hint: "Curved throwing weapon that returns" },
      { word: "ABACUS", hint: "Ancient counting tool with beads" },
    ]
  },
  general: {
    label: "General",
    icon: "🎯",
    color: "#FFC312",
    words: [
      { word: "ADVENTURE", hint: "An exciting or unusual experience" },
      { word: "BUTTERFLY", hint: "Insect that starts life as a caterpillar" },
      { word: "CHOCOLATE", hint: "Sweet treat made from cocoa beans" },
      { word: "DINOSAUR", hint: "Ancient reptile that lived millions of years ago" },
      { word: "ELEPHANT", hint: "Largest land animal with a long trunk" },
      { word: "FIREWORKS", hint: "Colorful explosions in the sky" },
      { word: "GIRAFFE", hint: "Tallest animal with a very long neck" },
      { word: "HURRICANE", hint: "Powerful tropical storm with strong winds" },
      { word: "ILLUSION", hint: "Something that tricks the eye or mind" },
      { word: "JELLYFISH", hint: "Sea creature with no brain or heart" },
      { word: "KNOWLEDGE", hint: "Information gained through learning" },
      { word: "LABYRINTH", hint: "A complicated irregular maze" },
      { word: "MOUNTAIN", hint: "A large natural elevation of the earth" },
      { word: "NIGHTMARE", hint: "A frightening dream" },
      { word: "OCEAN", hint: "A vast body of salt water" },
      { word: "PENGUIN", hint: "Flightless bird from Antarctica" },
      { word: "QUICKSAND", hint: "Loose wet sand that sucks things in" },
      { word: "RAINBOW", hint: "Colorful arc in sky after rain" },
      { word: "SKELETON", hint: "Framework of bones in a body" },
      { word: "TORNADO", hint: "Rotating column of air touching the ground" },
    ]
  }
};

// Save a new word added via multiplayer
function addWordToCategory(category, word, hint = "No hint provided") {
  if (WORD_DATA[category]) {
    WORD_DATA[category].words.push({ word: word.toUpperCase(), hint });
  }
}
